# User-Agent strings to exclude
#
# Case-sensitive regular expressions

# Ordinary indexers
[bB]ot[^a-zA-Z]
_bot$
Bot$
Yahoo
[cC]rawler
[sS]pider
[sS]ite[eE]xplorer
Deepnet
[fF]etcher
Media[pP]artners
yandex
archiver
panscient
ips-agent
Voyager
findlink
heritrix
[fF]acebook[eE]xternal[hH]it
Analyzer
ichiro
coccoc
binlar
A6-Indexer
Google-SearchByImage
FlipboardProxy
dataminr
Link

# Potentially malicious
Java/
wget
curl
libwww
